gamma: 0.99
tau: 0.005
lr_actor: 0.0003
lr_critic: 0.0003
batch_size: 512
buffer_size: 2000000
target_entropy: -1.0
updates_per_step: 1
encoder:
  type: vector
  hidden_units: [256, 256]
device: "cuda"
n_envs: 8
