expectile_beta: 0.8
temperature: 0.3
discount: 0.99
lr: 0.0003
batch_size: 256
grad_steps: 3000
compile_graph: true
actor_encoder_factory:
  type: vector
  params: { hidden_units: [256, 256] }
critic_encoder_factory:
  type: vector
  params: { hidden_units: [256, 256] }
value_encoder_factory:
  type: vector
  params: { hidden_units: [256, 256] }
device: "cuda"
